---
- name: "[Internal] Check for legacy statements"
  include_tasks: fix_legacy_terminology.yml
  when: my_ansible_version_point_min is defined

- name: "[Internal] Enhance Debugging"
  include_tasks: debug.yml
  when: my_ansible_version_debug|default('false')|string != 'false'

- name: Ansible Version Check
  assert:
    msg: "Requires Ansible {{ my_ansible_version_major_min|int }}.{{ my_ansible_version_minor_min|int }}.{{ my_ansible_version_revision_min|int }} or later - you have {{ ansible_version.major|int }}.{{ ansible_version.minor|int }}.{{ ansible_version.revision|int }}"
    that: (ansible_version.major|int == my_ansible_version_major_min|int and ansible_version.minor|int >= my_ansible_version_minor_min|int and ansible_version.revision|int >= my_ansible_version_revision_min) or (ansible_version.major|int == my_ansible_version_major_min|int and ansible_version.minor|int > my_ansible_version_minor_min) or (ansible_version.major|int > my_ansible_version_major_min)
